# reference:
# https://github.com/microsoft/edit/blob/main/Cargo.toml
# https://github.com/johnthagen/min-sized-rust

[alias]
br = "build --release"
rr = "run --release"

[profile.release]
panic = "immediate-abort"

[unstable]
panic-immediate-abort = true
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C","link-arg=-Wl,-z,pack-relative-relocs",
]
